spring:
  profiles:
    include: logback

  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    pas sword: 1234

  h2:
    console:
      enabled: true
      path: /h2-console